/* Themenkatalog, erzeugt aus den Ordnern in iCloud → 3_Unterrichtsstunden/Musikseminarsave.
   t = Thema, g = Jahrgangsstufen, f = Ordnername (zum Wiederfinden des Materials).
   Eigene Themen legst du direkt in der App an – die bleiben beim Aktualisieren erhalten. */
const TOPICS_SEED = [
 {"t": "1_aHuman Percussion Federmaeppchen", "g": [5], "f": "Klasse 5 - 1_aHuman Percussion Federmaeppchen"},
 {"t": "1_Notenwerte mit Bewegung Mip", "g": [5], "f": "Klasse 5 - 1_Notenwerte mit Bewegung Mip"},
 {"t": "1b_Rhythmus WH", "g": [5], "f": "Klasse 5 - 1b_Rhythmus WH"},
 {"t": "2_Stammtöne Noten lesen Schott", "g": [5], "f": "Klasse 5 - 2_Stammtöne Noten lesen Schott"},
 {"t": "3_Metrum Puls Tempo by phil", "g": [5], "f": "Klasse 5 - 3_Metrum Puls Tempo by phil"},
 {"t": "4_keyboard praxis - freude schöner", "g": [5], "f": "Klasse 5 - 4_keyboard praxis - freude schöner"},
 {"t": "Basteln Musik Vorlagen", "g": [5, 6, 7, 8, 9, 10], "f": "Klasse 5 - 10 Basteln Musik Vorlagen"},
 {"t": "Bodypercussion - Mozart Serail (nach mozart)", "g": [5], "f": "Klasse 5 - Bodypercussion - Mozart Serail (nach mozart)"},
 {"t": "Bodypercussion selber erfinden auch Vertretung", "g": [5, 6], "f": "Klasse 5 oder 6 - Bodypercussion selber erfinden auch Vertretung"},
 {"t": "Corona - Percussioninstrumente Musix Rund um die Stimme", "g": [5], "f": "Klasse 5 - Corona - Percussioninstrumente Musix Rund um die Stimme"},
 {"t": "Corona - Präsentaiton Band", "g": [5, 6, 7], "f": "Klasse 5-7 - Corona - Präsentaiton Band"},
 {"t": "Cotton Eye Joe - Mip 53-2018", "g": [5, 6], "f": "Klasse 5-6 - Cotton Eye Joe - Mip 53-2018"},
 {"t": "Cupsong when im gone", "g": [5], "f": "Klasse 5 - Cupsong  when im gone"},
 {"t": "Der Auftakt", "g": [5], "f": "Klasse 5 - Der Auftakt"},
 {"t": "die Moldau malen", "g": [5, 6, 7], "f": "Klasse 5-7 - die Moldau malen"},
 {"t": "Digitale Bildung - Arten der Tonaufzeichnung", "g": [5], "f": "Klasse 5 - Digitale Bildung - Arten der Tonaufzeichnung"},
 {"t": "Dreiklänge", "g": [5], "f": "Klasse 5 - Dreiklänge"},
 {"t": "Eingeschlossen im Musikhaus (Escape Room)", "g": [5, 6], "f": "Klasse 5-6 - Eingeschlossen im Musikhaus (Escape Room)"},
 {"t": "Erl josef stunde Everyday Beat", "g": [5, 6, 7, 8, 9, 10], "f": "Klasse 5-10 - Erl josef stunde Everyday Beat"},
 {"t": "Hörspiel Mozartsr. Musix Arbeitsheft", "g": [5], "f": "Klasse 5 - Hörspiel Mozartsr. Musix Arbeitsheft"},
 {"t": "Klassenmusizieren - Indianersong", "g": [5], "f": "Klasse 5 - Klassenmusizieren - Indianersong"},
 {"t": "Klassenmusizieren - Zwei kleine Wölfe", "g": [5], "f": "Klasse 5 - Klassenmusizieren - Zwei kleine Wölfe"},
 {"t": "Klassenmusizieren Ukulele - Kookaburra", "g": [5], "f": "Klasse 5 - Klassenmusizieren Ukulele - Kookaburra"},
 {"t": "Lapbooks Musik Lieblingsband", "g": [5], "f": "Klasse 5 - Lapbooks Musik Lieblingsband"},
 {"t": "Lesefoerderung - Grashalm Musik", "g": [5], "f": "Klasse 5 - Lesefoerderung - Grashalm Musik"},
 {"t": "Life is Life drumbeat", "g": [5, 6, 7, 8], "f": "Klasse 5-8 - Life is Life drumbeat"},
 {"t": "Notendetektive rätsel", "g": [5, 6], "f": "Klasse 5-6 - Notendetektive rätsel"},
 {"t": "Notenlesen Tonnamen oktavlagen", "g": [5], "f": "Klasse 5 - Notenlesen Tonnamen oktavlagen"},
 {"t": "Notenlesen übungen rätsel sammlung", "g": [5], "f": "Klasse 5 - Notenlesen übungen rätsel sammlung"},
 {"t": "Notenwerte, Metrum", "g": [5], "f": "Klasse 5 - Notenwerte, Metrum"},
 {"t": "Pausenwerte - vorher Taktarten!", "g": [5], "f": "Klasse 5 - Pausenwerte - vorher Taktarten!"},
 {"t": "Regeln Verhalten Konzert", "g": [5], "f": "Klasse 5 - Regeln Verhalten Konzert"},
 {"t": "Rhapsody in Blue", "g": [5], "f": "Klasse 5 - Rhapsody in Blue"},
 {"t": "Rhythmus-Takt", "g": [5], "f": "Klasse 5 - Rhythmus-Takt"},
 {"t": "rhythmusspiele drumsticks", "g": [5, 6], "f": "Klasse 5-6 - rhythmusspiele drumsticks"},
 {"t": "Schnelle Stunde Auer", "g": [5, 6, 7, 8, 9, 10], "f": "Klasse 5-10 Schnelle Stunde Auer"},
 {"t": "schott arbeitsheft alles", "g": [5, 6], "f": "klasse 5-6 - schott arbeitsheft alles"},
 {"t": "Sechzehntelübungen", "g": [5], "f": "Klasse 5 - Sechzehntelübungen"},
 {"t": "song maker Music Maker", "g": [5, 6], "f": "Klasse 5-6 - song maker Music Maker"},
 {"t": "Stationen Percussionsinstrumente", "g": [5], "f": "Klasse 5 - Stationen Percussionsinstrumente"},
 {"t": "Taktarten", "g": [5], "f": "Klasse 5 - Taktarten"},
 {"t": "Tanzen - Line Dance - Summertime Blues Mip 21-08", "g": [5], "f": "Klasse 5 - Tanzen - Line Dance - Summertime Blues Mip 21-08"},
 {"t": "Tanzen - Line Dance Texas Hold Em", "g": [5], "f": "Klasse 5 - Tanzen - Line Dance Texas Hold Em"},
 {"t": "Tempo Tempi mip", "g": [5], "f": "Klasse 5 - Tempo Tempi mip"},
 {"t": "Train Your Brain", "g": [5, 6, 7, 8, 9, 10], "f": "Klasse 1 - 10 - Train Your Brain"},
 {"t": "Violine", "g": [5], "f": "Klasse 5 - Violine"},
 {"t": "W.A. Mozart", "g": [5], "f": "Klasse 5 - W.A. Mozart"},
 {"t": "Warm-Ups", "g": [5, 6, 7, 8, 9, 10], "f": "Klasse 5-10 - Warm-Ups"},
 {"t": "Weihnachten - ipad - leise rieselt der schnee", "g": [5], "f": "Klasse 5 - Weihnachten - ipad - leise rieselt der schnee"},
 {"t": "Yellow Submarine Keyboard", "g": [5], "f": "Klasse 5 - Yellow Submarine Keyboard"},
 {"t": "1_Rhythmus praxis - Notenwerte drumscripts + praxis + mitspielsatz", "g": [6], "f": "Klasse 6 - 1_Rhythmus praxis - Notenwerte drumscripts + praxis + mitspielsatz"},
 {"t": "2_ Tube Drum Line", "g": [6], "f": "Klasse 6 - 2_ Tube Drum Line"},
 {"t": "2_KM - Shalalalala", "g": [6], "f": "Klasse 6 - 2_KM - Shalalalala"},
 {"t": "3.1_Instrumentalbesetzungen - Ensembles Musix", "g": [6], "f": "Klasse 6 - 3.1_Instrumentalbesetzungen - Ensembles Musix"},
 {"t": "3_Orchesterinstrumente - checker tobi", "g": [6], "f": "Klasse 6 - 3_Orchesterinstrumente - checker tobi"},
 {"t": "4_1wh Tonhöhen und versetzungszeichen", "g": [6], "f": "Klasse 6 - 4_1wh Tonhöhen und versetzungszeichen"},
 {"t": "4_Vorzeichen - Versetzungszeichen + Tonleitern", "g": [6], "f": "Klasse 6 - 4_Vorzeichen - Versetzungszeichen + Tonleitern"},
 {"t": "Barock Lernzirkel", "g": [6], "f": "Klasse 6 - Barock Lernzirkel"},
 {"t": "Becherpercussion Cup Savage Love", "g": [6], "f": "Klasse 6 - Becherpercussion Cup Savage Love"},
 {"t": "begging stops", "g": [6], "f": "Klasse 6 - begging stops"},
 {"t": "Believer Tischpercussion", "g": [6], "f": "Klasse 6 - Believer Tischpercussion"},
 {"t": "Bodypercussion - Klassenmusizieren - Tritsch Tratsch Polka", "g": [6], "f": "Klasse 6 - Bodypercussion - Klassenmusizieren - Tritsch Tratsch Polka"},
 {"t": "Chordofone _ Tasteninstrumente", "g": [6, 7], "f": "Klasse 6 - 7 - Chordofone _ Tasteninstrumente"},
 {"t": "Die Stimme", "g": [6], "f": "Klasse 6 - Die Stimme"},
 {"t": "Die with a Smile Bruno Mars Tischpercussion", "g": [6], "f": "Klasse 6 - Die with a Smile Bruno Mars  Tischpercussion"},
 {"t": "Dynamik - Lautstärken mit Grafik", "g": [6], "f": "Klasse 6 - Dynamik - Lautstärken mit Grafik"},
 {"t": "Fate Of Ophelia - Tanz MIP 75-26", "g": [6], "f": "Klasse 6 - Fate Of Ophelia - Tanz MIP 75-26"},
 {"t": "Groove Hier Bodyerc", "g": [6], "f": "Klasse 6 Groove Hier Bodyerc"},
 {"t": "Intervalle dur tonleiter halbton ganzton", "g": [6], "f": "Klasse 6 - Intervalle dur tonleiter halbton ganzton"},
 {"t": "is mir egal", "g": [6], "f": "Klasse 6 - is mir egal"},
 {"t": "Jahreszeiten", "g": [6], "f": "Klasse 6 Jahreszeiten"},
 {"t": "keyboard - In The End", "g": [6], "f": "Klasse 6 - keyboard - In The End"},
 {"t": "Klassenmusizieren - Fußball - Rap-selber dichten", "g": [6], "f": "Klasse 6 - Klassenmusizieren - Fußball - Rap-selber dichten"},
 {"t": "Klassenmusizieren - Keine Maschine", "g": [6], "f": "Klasse 6 - Klassenmusizieren - Keine Maschine"},
 {"t": "Klassenmusizieren Mary's Boychild + Warmup", "g": [6], "f": "Klasse 6 - Klassenmusizieren Mary's Boychild + Warmup"},
 {"t": "Klassenmusizieren Mitspielsatz Mama Mia", "g": [6, 7, 8, 9], "f": "Klasse 6-9 - Klassenmusizieren Mitspielsatz Mama Mia"},
 {"t": "Klaviatur lesen", "g": [6], "f": "Klasse 6 - Klaviatur lesen"},
 {"t": "KM - Iko Iko", "g": [6], "f": "Klasse 6 - KM - Iko Iko"},
 {"t": "Linkin Park - Mondnacht", "g": [6], "f": "Klasse 6 - Linkin Park - Mondnacht"},
 {"t": "Motiv-Liedformen", "g": [6], "f": "Klasse 6 - Motiv-Liedformen"},
 {"t": "Musical Checker Tobi mit Fragen", "g": [6, 7, 8], "f": "Klasse 6-8 - Musical Checker Tobi mit Fragen"},
 {"t": "Notenleseübung+Klassenmusizieren(Without you)", "g": [6], "f": "Klasse 6 - Notenleseübung+Klassenmusizieren(Without you)"},
 {"t": "Notennamen, Tonhöhen, Register", "g": [6], "f": "Klasse 6 - Notennamen, Tonhöhen, Register"},
 {"t": "old Orchesterinstrumente (Sequenz)", "g": [6], "f": "Klasse 6 - old Orchesterinstrumente (Sequenz)"},
 {"t": "Orchesterinstrumente 2 - Kisum MusiX", "g": [6], "f": "Klasse 6 - Orchesterinstrumente 2 - Kisum MusiX"},
 {"t": "Programmmusik", "g": [6], "f": "Klasse 6 - Programmmusik"},
 {"t": "Programmmusik MusiX", "g": [6], "f": "Klasse 6 - Programmmusik MusiX"},
 {"t": "Rhythmus- Bodypercussion -Rap- wir sind die Klasse", "g": [6], "f": "Klasse 6 - Rhythmus- Bodypercussion -Rap- wir sind die Klasse"},
 {"t": "Rhythmusspiel-Codenames-test", "g": [6], "f": "Klasse 6 - Rhythmusspiel-Codenames-test"},
 {"t": "Rohrsalat percussion muell", "g": [6], "f": "Klasse 6 - Rohrsalat percussion muell"},
 {"t": "Rollenspiel Biografie Bach", "g": [6], "f": "Klasse 6 - Rollenspiel Biografie Bach"},
 {"t": "Salibonani", "g": [6, 7], "f": "Klasse 6-7 - Salibonani"},
 {"t": "Song Summen Quiz game", "g": [6], "f": "Klasse 6 - Song Summen Quiz game"},
 {"t": "Sprechstück Guten Morgen", "g": [6], "f": "Klasse 6 - Sprechstück Guten Morgen"},
 {"t": "Tonhöhen MIP", "g": [6], "f": "Klasse 6 - Tonhöhen MIP"},
 {"t": "Tonleiter", "g": [6], "f": "Klasse 6 - Tonleiter"},
 {"t": "Ukulele - 9 bis 9", "g": [6], "f": "Klasse 6 - Ukulele - 9 bis 9"},
 {"t": "Ukulele - Avicii - Wake me up", "g": [6, 7, 8], "f": "Klasse 6 - 8 Ukulele - Avicii - Wake me up"},
 {"t": "Ukulele Happier", "g": [6], "f": "Klasse 6 - Ukulele Happier"},
 {"t": "Unterschied Rockkonzert : Klassikkonzert", "g": [6], "f": "Klasse 6 - Unterschied Rockkonzert : Klassikkonzert"},
 {"t": "Urheberrecht", "g": [6], "f": "Klasse 6 - Urheberrecht"},
 {"t": "Vocussion Einheit", "g": [6], "f": "Klasse 6 - Vocussion Einheit"},
 {"t": "We celebrate_Becherpercussion", "g": [6], "f": "Klasse 6 - We celebrate_Becherpercussion"},
 {"t": "Weihnachten - iPad Jingle Bells erster Song", "g": [6], "f": "Klasse 6 - Weihnachten - iPad Jingle Bells erster Song"},
 {"t": "1_Die Bandinstrumente", "g": [7], "f": "Klasse 7 - 1_Die Bandinstrumente"},
 {"t": "2.1 iPad Garage Band Gitarre", "g": [7], "f": "Klasse 7 - 2.1 iPad Garage Band Gitarre"},
 {"t": "2.2 Musik und Werbung", "g": [7], "f": "Klasse 7 - 2.2 Musik und Werbung"},
 {"t": "2_Die E-Gitarre", "g": [7], "f": "Klasse 7 - 2_Die E-Gitarre"},
 {"t": "3_LP - drums", "g": [7], "f": "Klasse 7 - 3_LP - drums"},
 {"t": "4.1- Montero Tischpercussion + eigene Pericussion", "g": [7], "f": "Klasse 7 - 4.1- Montero Tischpercussion + eigene Pericussion"},
 {"t": "4.2_tischpercussion drumbeats Helbling", "g": [7], "f": "Klasse 7 - 4.2_tischpercussion drumbeats Helbling"},
 {"t": "4_drumgrooves", "g": [7], "f": "Klasse 7 - 4_drumgrooves"},
 {"t": "5_Der E-Bass", "g": [7], "f": "Klasse 7 - 5_Der E-Bass"},
 {"t": "Antonio Vivaldi (aus MIP)", "g": [7], "f": "Klasse 7 - Antonio Vivaldi (aus MIP)"},
 {"t": "Archetypen", "g": [7, 8], "f": "Klasse 7-8 - Archetypen"},
 {"t": "Barock-Einführung", "g": [7], "f": "Klasse 7 - Barock-Einführung"},
 {"t": "Billie Eilish", "g": [7], "f": "Klasse 7 - Billie Eilish"},
 {"t": "Concerto grosso", "g": [7], "f": "Klasse 7 - Concerto grosso"},
 {"t": "corona - Klassenmusizieren - blinding lights", "g": [7], "f": "Klasse 7 - corona - Klassenmusizieren - blinding lights"},
 {"t": "Der E-Bass (oli, video musix)", "g": [7], "f": "Klasse 7 - Der E-Bass (oli, video musix)"},
 {"t": "Der Rap Hack", "g": [7, 8], "f": "Klasse 7 oder 8 - Der Rap Hack"},
 {"t": "Duett Drumscripts", "g": [7], "f": "Klasse 7 - Duett Drumscripts"},
 {"t": "Echoverleihung", "g": [7], "f": "Klasse 7 - Echoverleihung"},
 {"t": "First Step Interstellar Keyboard", "g": [7], "f": "Klasse 7 - First Step Interstellar Keyboard"},
 {"t": "garageband - gstanzl", "g": [7, 8, 9], "f": "klasse 7-9 - garageband - gstanzl"},
 {"t": "iPad I Like The Flowers Garage Band", "g": [7], "f": "Klasse 7 - iPad I Like The Flowers Garage Band"},
 {"t": "J.S. Bach Stunde Tom", "g": [7], "f": "Klasse 7 - J.S. Bach Stunde Tom"},
 {"t": "Johann Sebastian Bach", "g": [7], "f": "Klasse 7 - Johann Sebastian Bach"},
 {"t": "Klassenmusizieren - Ho Hey", "g": [7, 8, 9], "f": "Klasse 7-9 Klassenmusizieren - Ho Hey"},
 {"t": "Klassenmusizieren - Riptide - Vance Jpy", "g": [7], "f": "Klasse 7 - Klassenmusizieren - Riptide - Vance Jpy"},
 {"t": "Klassenmusizieren - Sowieso", "g": [7], "f": "Klasse 7 - Klassenmusizieren - Sowieso"},
 {"t": "Klassenmusizieren - War Is Over", "g": [7], "f": "Klasse 7 - Klassenmusizieren - War Is Over"},
 {"t": "Lady Gaga", "g": [7], "f": "Klasse 7 - Lady Gaga"},
 {"t": "MGK dont let me go Pen percussion", "g": [7], "f": "Klasse 7 - MGK dont let me go Pen percussion"},
 {"t": "Nach Gitarre - iPad Garage Band", "g": [7], "f": "Klasse 7 - Nach Gitarre - iPad Garage Band"},
 {"t": "Percussion mit muell", "g": [7], "f": "Klasse 7 - Percussion mit muell"},
 {"t": "Pop und Identität - Ich und mein Sound - Musikselfie", "g": [7], "f": "Klasse 7 - Pop und Identität - Ich und mein Sound - Musikselfie"},
 {"t": "Popmusic Around The World", "g": [7], "f": "Klasse 7 - Popmusic Around The World"},
 {"t": "Singstunde", "g": [7], "f": "Klasse 7 - Singstunde"},
 {"t": "Skrillex", "g": [7, 8], "f": "Klasse 7-8 - Skrillex"},
 {"t": "Star Mix Rätsel Knobeln", "g": [7, 8, 9, 10], "f": "Klasse 7-10 - Star Mix Rätsel Knobeln"},
 {"t": "Tanz - About Damn Time Mip 65", "g": [7, 8], "f": "Klasse 7-8 - Tanz - About Damn Time Mip 65"},
 {"t": "Tanz - Ghost Mip 64", "g": [7, 8], "f": "Klasse 7-8 - Tanz - Ghost Mip 64"},
 {"t": "Taylor Swift", "g": [7], "f": "Klasse 7 - Taylor Swift"},
 {"t": "Vertretung - Recherche Lieblingssong", "g": [7, 8, 9, 10], "f": "Klasse 7 - 10 Vertretung - Recherche Lieblingssong"},
 {"t": "Warmup+Wiederholung Te deum", "g": [7], "f": "Klasse 7 - Warmup+Wiederholung Te deum"},
 {"t": "Wiener Klassik", "g": [7], "f": "Klasse 7 (LP neu) 8e - Wiener Klassik"},
 {"t": "Bass spielen", "g": [8], "f": "Klasse 8e - Bass spielen"},
 {"t": "beat it", "g": [8, 9], "f": "Klasse 8-9 beat it"},
 {"t": "Bodypercussion inkl. Gruppenarbeit", "g": [8], "f": "Klasse 8 - Bodypercussion inkl. Gruppenarbeit"},
 {"t": "Corona Musikbusiness", "g": [8, 9, 10], "f": "Klasse 8 -10 - Corona Musikbusiness"},
 {"t": "dirigier workshop mit videos", "g": [8, 9], "f": "Klasse 8 - 9 - dirigier workshop mit videos"},
 {"t": "dirigier workshop ohne videos", "g": [8, 9], "f": "Klasse 8 - 9 - dirigier workshop ohne videos"},
 {"t": "Get Lucky Ukulele", "g": [8], "f": "Klasse 8 - Get Lucky Ukulele"},
 {"t": "ipad begleitung", "g": [8, 9], "f": "Klasse 8-9 - ipad begleitung"},
 {"t": "Jazz", "g": [8], "f": "Klasse 8d - Jazz"},
 {"t": "Jazz", "g": [8], "f": "Klasse 8e - Jazz"},
 {"t": "Klassenmusizieren - Hold Back The River", "g": [8], "f": "Klasse 8 - Klassenmusizieren - Hold Back The River"},
 {"t": "Klassenmusizieren - Tischpercussion (Leaving On A Jetplane)", "g": [8], "f": "Klasse 8 - Klassenmusizieren - Tischpercussion (Leaving On A Jetplane)"},
 {"t": "MP3 qualität", "g": [8, 9], "f": "Klasse 8-9 - MP3 qualität"},
 {"t": "Musikproduktion", "g": [8, 9, 10], "f": "Klasse 8 - 10  - Musikproduktion"},
 {"t": "Musikproduktion 2 - Mip 59-2020", "g": [8, 9, 10], "f": "Klasse 8 - 10 - Musikproduktion 2 - Mip 59-2020"},
 {"t": "Referate Jazz", "g": [8], "f": "Klasse 8 - Referate Jazz"},
 {"t": "Reggaetone Cajon Stunde", "g": [8, 9, 10], "f": "Klasse 8-10 - Reggaetone Cajon Stunde"},
 {"t": "Spirituals - Worksongs - Blues 2019 Version", "g": [8], "f": "Klasse 8 - Spirituals - Worksongs - Blues 2019 Version"},
 {"t": "Ukulele - Stand By Me", "g": [8, 9, 10], "f": "Klasse 8-10 Ukulele - Stand By Me"},
 {"t": "Ukulele blues Shuffle", "g": [8], "f": "Klasse 8 - Ukulele blues Shuffle"},
 {"t": "welche Musik gefällt euch", "g": [8], "f": "Klasse 8e - welche Musik gefällt euch"},
 {"t": "1 Einführung Rock- und Popmusik", "g": [9], "f": "Klasse 9 - 1 Einführung Rock- und Popmusik"},
 {"t": "2 Rock- und Popmusik", "g": [9], "f": "Klasse 9 - 2 Rock- und Popmusik"},
 {"t": "Die Beatles", "g": [9], "f": "Klasse 9 - Die Beatles"},
 {"t": "Don Giovanni", "g": [9], "f": "Klasse 9 - Don Giovanni"},
 {"t": "Ed Sheeran Starportrait", "g": [9, 10], "f": "Klasse 9-10 - Ed Sheeran Starportrait"},
 {"t": "Elvis Presley", "g": [9], "f": "Klasse 9 - Elvis Presley"},
 {"t": "Fluch der Karibik - Hes A Pirate Ukulele", "g": [9], "f": "Klasse 9 - Fluch der Karibik - Hes A Pirate Ukulele"},
 {"t": "Klassenmusizieren - Stay With Me", "g": [9], "f": "Klasse 9 - Klassenmusizieren - Stay With Me"},
 {"t": "Klassenmusizieren - Without You", "g": [9], "f": "Klasse 9 - Klassenmusizieren - Without You"},
 {"t": "mip es ist zeit eigener rap", "g": [9], "f": "Klasse 9 - mip es ist zeit eigener rap"},
 {"t": "Musikindustrie Markt", "g": [9], "f": "Klasse 9 - Musikindustrie Markt"},
 {"t": "Oper", "g": [9], "f": "Klasse 9 - Oper"},
 {"t": "Riptide Ukulele", "g": [9], "f": "Klasse 9 - Riptide Ukulele"},
 {"t": "Save Your Tears", "g": [9], "f": "Klasse 9 - Save Your Tears"},
 {"t": "Sleep Token", "g": [9], "f": "Klasse 9 - Sleep Token"},
 {"t": "Stile der Populären Musik", "g": [9], "f": "Klasse 9 -  Stile der Populären Musik"},
 {"t": "Storyboard Adobe Spark", "g": [9], "f": "Klasse 9 - Storyboard Adobe Spark"},
 {"t": "Urheberrecht", "g": [9, 10], "f": "Klasse 9-10 - Urheberrecht"},
 {"t": "Beatboxing", "g": [10], "f": "Klasse 10 - Beatboxing"},
 {"t": "Don Juan - Don Giovanni", "g": [10], "f": "Klasse 10 - Don Juan - Don Giovanni"},
 {"t": "Klassenmusizieren", "g": [10], "f": "Klasse 10 - Klassenmusizieren"},
 {"t": "Politisches Lied - Referatsthemen", "g": [10], "f": "Klasse 10 - Politisches Lied - Referatsthemen"},
 {"t": "Referate Citizenship", "g": [10], "f": "Klasse 10 - Referate Citizenship"},
 {"t": "sticktricks", "g": [10], "f": "klasse 10 - sticktricks"},
 {"t": "Table Desktop drumming bodyperc", "g": [10], "f": "Klasse 10 - Table Desktop drumming bodyperc"},
 {"t": "TikTok challenge", "g": [10], "f": "Klasse 10 - TikTok challenge"},
 {"t": "Ukulele", "g": [10], "f": "Klasse 10 - Ukulele"},
 {"t": "1a Klassenmusizieren various", "g": [], "f": "1a Klassenmusizieren various"},
 {"t": "5 by Phil", "g": [], "f": "5 by Phil"},
 {"t": "5 erste Stunde meine musik deine musik", "g": [], "f": "Klasse 1 5 erste Stunde meine musik deine musik"},
 {"t": "Corona - Ankommen Kommunikation", "g": [], "f": "Corona - Ankommen Kommunikation"},
 {"t": "Drum Circle Cajon", "g": [], "f": "Drum Circle Cajon"},
 {"t": "Earz", "g": [], "f": "Earz"},
 {"t": "End Of Beginning", "g": [], "f": "End Of Beginning"},
 {"t": "feedback abschluss letzte stunde", "g": [], "f": "feedback abschluss letzte stunde"},
 {"t": "guten morgen - bodypercussion", "g": [], "f": "guten morgen - bodypercussion"},
 {"t": "hubi", "g": [], "f": "hubi"},
 {"t": "ipad garage band neu", "g": [], "f": "ipad garage band neu"},
 {"t": "Jazz-Sammlung", "g": [], "f": "Jazz-Sammlung"},
 {"t": "Musik in der Coronakriese", "g": [], "f": "Musik in der Coronakriese"},
 {"t": "Tonleiter", "g": [], "f": "Tonleiter"},
 {"t": "Verfassungsviertelstunde", "g": [], "f": "Verfassungsviertelstunde"},
 {"t": "zusatzaufgabe", "g": [], "f": "zusatzaufgabe"},
];
